/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.cauegallizzi.clientregistryswing;

public class App {
    public static void main(String[] args) {
        Home home = new Home();
        home.setVisible(true);
    }
}
