/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.cauegallizzi.clientregistryswing;

import dev.cauegallizzi.dao.ClientMapDAO;
import dev.cauegallizzi.dao.IClientDAO;
import dev.cauegallizzi.domain.Client;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caueg
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());
    private DefaultTableModel model = new DefaultTableModel();
    private IClientDAO clientDAO = new ClientMapDAO();

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        Title = new javax.swing.JTextPane();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        CPFLabel = new javax.swing.JLabel();
        CPFField = new javax.swing.JTextField();
        TelLabel = new javax.swing.JLabel();
        TelField = new javax.swing.JTextField();
        CityField = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        StateLabel = new javax.swing.JLabel();
        StateField = new javax.swing.JTextField();
        NumberLabel = new javax.swing.JLabel();
        NumberField = new javax.swing.JTextField();
        EndLabel = new javax.swing.JLabel();
        EndField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatabaseTable = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        Title.setText("Client Registry System");
        jScrollPane1.setViewportView(Title);

        NameLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        NameLabel.setText("Name");

        NameField.addActionListener(this::NameFieldActionPerformed);

        CPFLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        CPFLabel.setText("CPF");

        CPFField.addActionListener(this::CPFFieldActionPerformed);

        TelLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        TelLabel.setText("Tel");

        TelField.addActionListener(this::TelFieldActionPerformed);

        CityField.addActionListener(this::CityFieldActionPerformed);

        CityLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        CityLabel.setText("City");

        StateLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        StateLabel.setText("State");

        StateField.addActionListener(this::StateFieldActionPerformed);

        NumberLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        NumberLabel.setText("Number");

        NumberField.addActionListener(this::NumberFieldActionPerformed);

        EndLabel.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        EndLabel.setText("End");

        EndField.addActionListener(this::EndFieldActionPerformed);

        SaveButton.setText("Save");
        SaveButton.addActionListener(this::SaveButtonActionPerformed);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(this::UpdateButtonActionPerformed);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(this::DeleteButtonActionPerformed);

        DatabaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DatabaseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatabaseTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DatabaseTable);

        FileMenu.setText("File");

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(this::ExitMenuItemActionPerformed);
        FileMenu.add(ExitMenuItem);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(NameLabel)
                            .addComponent(NameField)
                            .addComponent(NumberLabel)
                            .addComponent(NumberField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPFLabel)
                                    .addComponent(CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TelLabel)
                                    .addComponent(TelField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CityLabel)
                                    .addComponent(CityField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StateLabel)
                                    .addComponent(StateField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(EndLabel)
                            .addComponent(EndField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CPFLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CPFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EndLabel)
                        .addGap(28, 28, 28)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        int result = JOptionPane.showConfirmDialog(
                this, 
                "You want to leave?", 
                "Leave",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void CPFFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFFieldActionPerformed

    private void TelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelFieldActionPerformed

    private void CityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityFieldActionPerformed

    private void NumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberFieldActionPerformed

    private void EndFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String name = NameField.getText();
        String cpf = CPFField.getText();
        String tel = TelField.getText();
        String city = CityField.getText();
        String state = StateField.getText();
        String number = NumberField.getText();
        String end = EndField.getText();
        
        if (!validFields(name, cpf, tel, city, state, number, end)) {
            JOptionPane.showMessageDialog(null, "All the fiels must be filled in");
            return;
        }
        
        Client client = new Client(name, cpf, tel, end, Integer.valueOf(number), city, state);
        Boolean created = clientDAO.Create(client);
        
        if (!created) {
            JOptionPane.showMessageDialog(null, "This client has already been registered", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        model.addRow(new Object[]{ client.getName(), client.getCpf(), client.getTel(), client.getEnd(), client.getNumber(), client.getCity(), client.getState()});
        cleanFields();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        int selectedRow = DatabaseTable.getSelectedRow();
        
        if (!(selectedRow >= 0)) { return; } 
        
        String name = NameField.getText();
        String cpf = CPFField.getText();
        String tel = TelField.getText();
        String city = CityField.getText();
        String state = StateField.getText();
        String number = NumberField.getText();
        String end = EndField.getText();
        
        if (!validFields(name, cpf, tel, city, state, number, end)) {
            JOptionPane.showMessageDialog(null, "All the fiels must be filled in");
            return;
        }
        
        Client client = new Client(name, cpf, tel, end, Integer.valueOf(number), city, state);
        clientDAO.Update(client);
        
        model.removeRow(selectedRow);
        model.addRow(new Object[]{ client.getName(), client.getCpf(), client.getTel(), client.getEnd(), client.getNumber(), client.getCity(), client.getState()});
        cleanFields();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int selectedRow = DatabaseTable.getSelectedRow();
        
        if (!(selectedRow >= 0)) { return; } 
        
        Long cpf = (Long) DatabaseTable.getValueAt(selectedRow, 1);
        
        int confirmDelete = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete this client?",
                "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
                );
        
        if (confirmDelete == JOptionPane.NO_OPTION) { return; } 
        
        clientDAO.Delete(cpf);
        model.removeRow(selectedRow);
        
        cleanFields();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void StateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateFieldActionPerformed

    private void DatabaseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatabaseTableMouseClicked
        int selectedRow = DatabaseTable.getSelectedRow();
        Long cpf = (Long) DatabaseTable.getValueAt(selectedRow, 1);
        Client client = clientDAO.Read(cpf);
        
        if (client == null) { return; }  
        
        NameField.setText(client.getName());
        CPFField.setText(client.getCpf().toString());
        TelField.setText(client.getTel().toString());
        CityField.setText(client.getCity());
        StateField.setText(client.getState());
        NumberField.setText(client.getNumber().toString());
        EndField.setText(client.getEnd());
    }//GEN-LAST:event_DatabaseTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPFField;
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JTextField CityField;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTable DatabaseTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField EndField;
    private javax.swing.JLabel EndLabel;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NumberField;
    private javax.swing.JLabel NumberLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField StateField;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JTextField TelField;
    private javax.swing.JLabel TelLabel;
    private javax.swing.JTextPane Title;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private boolean validFields(String ...fields) {
       for (String field : fields) {
           if (field == null || "".equals(field)) {
               return false;
           }
       }
       return true;
    }
    
    private void cleanFields() {
        NameField.setText("");
        CPFField.setText("");
        TelField.setText("");
        CityField.setText("");
        StateField.setText("");
        NumberField.setText("");
        EndField.setText("");
    }
    
    private void initCustomComponents() {
        model.addColumn("Name");
        model.addColumn("CPF");
        model.addColumn("Tel");
        model.addColumn("End");
        model.addColumn("Number");
        model.addColumn("City");
        model.addColumn("State");
        
        DatabaseTable.setModel(model);
    }
}
